### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/regex4ls#1]
Could you confirm if the repo is still active and needed? To do so, just close this issue by end of Feb 2024. If not, we'll archive the repo. The repo can still be unarchived, so it's not a destructive action.

**Comment by albers** [comment]
It is unlikely that there will be further development in this project.
Its scope is very narrow and it is feature-complete.

But I think the project is still relevant for legacy applications. We still use it in some applications.

If archieving means that the project is just being switched to a read-only status, I' fine with that.

**Comment by paulswithers** [comment]
Yes, that's correct, it will just be read only. Thanks for updating us.
